-- archivo: database/sql/03_schema.sql
\connect siged_pnp;

CREATE TABLE IF NOT EXISTS delitos (
    id_delito SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_delito VARCHAR(120) NOT NULL UNIQUE,
    descripcion VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS comisarias (
    id_comisaria SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_comisaria VARCHAR(150) NOT NULL,
    distrito VARCHAR(100) NOT NULL,
    direccion VARCHAR(200)
);

CREATE TABLE IF NOT EXISTS eventos_delictivos (
    id_evento BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha DATE NOT NULL,
    hora TIME NOT NULL,
    id_delito SMALLINT NOT NULL,
    distrito VARCHAR(100) NOT NULL,
    direccion VARCHAR(200) NOT NULL,
    latitud NUMERIC(9,6) NOT NULL,
    longitud NUMERIC(9,6) NOT NULL,
    geom geometry(Point, 4326) NOT NULL,
    id_comisaria SMALLINT,
    fuente_registro VARCHAR(100) NOT NULL,
    descripcion TEXT,
    CONSTRAINT fk_eventos_delito
        FOREIGN KEY (id_delito)
        REFERENCES delitos (id_delito),
    CONSTRAINT fk_eventos_comisaria
        FOREIGN KEY (id_comisaria)
        REFERENCES comisarias (id_comisaria),
    CONSTRAINT chk_latitud_rango
        CHECK (latitud BETWEEN -90 AND 90),
    CONSTRAINT chk_longitud_rango
        CHECK (longitud BETWEEN -180 AND 180)
);
