-- archivo: database/sql/06_lotes_staging.sql
\connect siged_pnp;

CREATE TABLE IF NOT EXISTS lotes_carga (
    id_lote BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_archivo VARCHAR(255) NOT NULL,
    ruta_archivo VARCHAR(500),
    estado_lote VARCHAR(30) NOT NULL DEFAULT 'PENDIENTE',
    total_filas INTEGER NOT NULL DEFAULT 0,
    filas_validas INTEGER NOT NULL DEFAULT 0,
    filas_error INTEGER NOT NULL DEFAULT 0,
    filas_promovidas INTEGER NOT NULL DEFAULT 0,
    observaciones TEXT,
    fecha_inicio TIMESTAMP NOT NULL DEFAULT NOW(),
    fecha_fin TIMESTAMP,
    CONSTRAINT chk_lotes_estado
        CHECK (estado_lote IN ('PENDIENTE', 'PROCESANDO', 'COMPLETADO', 'COMPLETADO_CON_ERRORES', 'FALLIDO'))
);

CREATE TABLE IF NOT EXISTS staging_eventos (
    id_staging BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_lote BIGINT NOT NULL,
    numero_fila INTEGER NOT NULL,
    fecha_raw VARCHAR(50),
    hora_raw VARCHAR(20),
    id_delito_raw VARCHAR(20),
    distrito_raw VARCHAR(100),
    direccion_raw VARCHAR(200),
    latitud_raw VARCHAR(50),
    longitud_raw VARCHAR(50),
    id_comisaria_raw VARCHAR(20),
    fuente_registro_raw VARCHAR(100),
    descripcion_raw TEXT,
    fecha DATE,
    hora TIME,
    id_delito SMALLINT,
    distrito VARCHAR(100),
    direccion VARCHAR(200),
    latitud NUMERIC(9,6),
    longitud NUMERIC(9,6),
    id_comisaria SMALLINT,
    fuente_registro VARCHAR(100),
    descripcion TEXT,
    estado_registro VARCHAR(30) NOT NULL DEFAULT 'PENDIENTE',
    mensaje_error TEXT,
    id_evento_final BIGINT,
    fecha_validacion TIMESTAMP,
    fecha_promocion TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_staging_lote
        FOREIGN KEY (id_lote)
        REFERENCES lotes_carga (id_lote),
    CONSTRAINT uq_staging_lote_fila
        UNIQUE (id_lote, numero_fila),
    CONSTRAINT chk_staging_estado
        CHECK (
            estado_registro IN (
                'PENDIENTE',
                'VALIDO',
                'ERROR_VALIDACION',
                'PROMOVIDO',
                'ERROR_PROMOCION',
                'ERROR_DUPLICADO'
            )
        )
);

CREATE INDEX IF NOT EXISTS idx_lotes_estado
    ON lotes_carga (estado_lote);

CREATE INDEX IF NOT EXISTS idx_staging_id_lote
    ON staging_eventos (id_lote);

CREATE INDEX IF NOT EXISTS idx_staging_lote_estado
    ON staging_eventos (id_lote, estado_registro);
