-- archivo: database/sql/08_zonas_operativas.sql
\connect siged_pnp;

CREATE TABLE IF NOT EXISTS zonas_operativas (
    id_zona BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo_zona VARCHAR(30) NOT NULL,
    nombre_zona VARCHAR(150) NOT NULL,
    tipo_zona VARCHAR(30) NOT NULL DEFAULT 'OPERATIVA',
    distrito VARCHAR(100) NOT NULL,
    id_comisaria SMALLINT,
    prioridad_operativa VARCHAR(20) NOT NULL DEFAULT 'MEDIA',
    estado_zona VARCHAR(20) NOT NULL DEFAULT 'ACTIVA',
    descripcion TEXT,
    geom geometry(MultiPolygon, 4326) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_zonas_operativas_codigo
        UNIQUE (codigo_zona),
    CONSTRAINT fk_zonas_comisaria
        FOREIGN KEY (id_comisaria)
        REFERENCES comisarias (id_comisaria),
    CONSTRAINT chk_zonas_tipo
        CHECK (tipo_zona IN ('OPERATIVA', 'CUADRANTE', 'SECTOR', 'JURISDICCION', 'PATRULLAJE')),
    CONSTRAINT chk_zonas_prioridad
        CHECK (prioridad_operativa IN ('BAJA', 'MEDIA', 'ALTA', 'CRITICA')),
    CONSTRAINT chk_zonas_estado
        CHECK (estado_zona IN ('ACTIVA', 'INACTIVA'))
);

CREATE INDEX IF NOT EXISTS idx_zonas_operativas_distrito
    ON zonas_operativas (distrito);

CREATE INDEX IF NOT EXISTS idx_zonas_operativas_id_comisaria
    ON zonas_operativas (id_comisaria);

CREATE INDEX IF NOT EXISTS idx_zonas_operativas_estado
    ON zonas_operativas (estado_zona);

CREATE INDEX IF NOT EXISTS idx_zonas_operativas_tipo
    ON zonas_operativas (tipo_zona);

CREATE INDEX IF NOT EXISTS idx_zonas_operativas_geom_gist
    ON zonas_operativas
    USING GIST (geom);
