-- archivo: database/sql/09_hotspots.sql
\connect siged_pnp;

CREATE TABLE IF NOT EXISTS hotspots (
    id_hotspot BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    periodo_inicio DATE NOT NULL,
    periodo_fin DATE NOT NULL,
    fecha_deteccion TIMESTAMP NOT NULL DEFAULT NOW(),
    id_delito SMALLINT,
    distrito VARCHAR(100) NOT NULL,
    id_zona BIGINT,
    nivel_riesgo VARCHAR(20) NOT NULL DEFAULT 'MEDIO',
    intensidad NUMERIC(10,2) NOT NULL DEFAULT 1.00,
    conteo_eventos INTEGER NOT NULL DEFAULT 0,
    latitud NUMERIC(9,6) NOT NULL,
    longitud NUMERIC(9,6) NOT NULL,
    geom geometry(Point, 4326) NOT NULL,
    radio_metros INTEGER NOT NULL DEFAULT 250,
    fuente_analisis VARCHAR(100) NOT NULL DEFAULT 'ANALISIS_MANUAL',
    estado_hotspot VARCHAR(20) NOT NULL DEFAULT 'ACTIVO',
    observaciones TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_hotspots_delito
        FOREIGN KEY (id_delito)
        REFERENCES delitos (id_delito),
    CONSTRAINT fk_hotspots_zona
        FOREIGN KEY (id_zona)
        REFERENCES zonas_operativas (id_zona),
    CONSTRAINT chk_hotspots_periodo
        CHECK (periodo_inicio <= periodo_fin),
    CONSTRAINT chk_hotspots_nivel
        CHECK (nivel_riesgo IN ('BAJO', 'MEDIO', 'ALTO', 'CRITICO')),
    CONSTRAINT chk_hotspots_estado
        CHECK (estado_hotspot IN ('ACTIVO', 'MITIGADO', 'INACTIVO')),
    CONSTRAINT chk_hotspots_latitud
        CHECK (latitud BETWEEN -90 AND 90),
    CONSTRAINT chk_hotspots_longitud
        CHECK (longitud BETWEEN -180 AND 180),
    CONSTRAINT chk_hotspots_radio
        CHECK (radio_metros > 0),
    CONSTRAINT chk_hotspots_intensidad
        CHECK (intensidad >= 0),
    CONSTRAINT chk_hotspots_conteo
        CHECK (conteo_eventos >= 0)
);

CREATE INDEX IF NOT EXISTS idx_hotspots_periodo
    ON hotspots (periodo_inicio, periodo_fin);

CREATE INDEX IF NOT EXISTS idx_hotspots_distrito
    ON hotspots (distrito);

CREATE INDEX IF NOT EXISTS idx_hotspots_id_delito
    ON hotspots (id_delito);

CREATE INDEX IF NOT EXISTS idx_hotspots_id_zona
    ON hotspots (id_zona);

CREATE INDEX IF NOT EXISTS idx_hotspots_estado
    ON hotspots (estado_hotspot);

CREATE INDEX IF NOT EXISTS idx_hotspots_nivel
    ON hotspots (nivel_riesgo);

CREATE INDEX IF NOT EXISTS idx_hotspots_geom_gist
    ON hotspots
    USING GIST (geom);
