-- archivo: database/sql/10_recomendaciones_patrullaje.sql
\connect siged_pnp;

CREATE TABLE IF NOT EXISTS recomendaciones_patrullaje (
    id_recomendacion BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha_generacion TIMESTAMP NOT NULL DEFAULT NOW(),
    fecha_operativa DATE NOT NULL DEFAULT CURRENT_DATE,
    turno VARCHAR(20) NOT NULL,
    id_hotspot BIGINT,
    id_zona BIGINT,
    id_comisaria SMALLINT,
    distrito VARCHAR(100) NOT NULL,
    prioridad VARCHAR(20) NOT NULL DEFAULT 'MEDIA',
    tipo_recomendacion VARCHAR(50) NOT NULL DEFAULT 'PATRULLAJE_PREVENTIVO',
    detalle_operativo TEXT NOT NULL,
    cantidad_efectivos SMALLINT,
    cantidad_unidades SMALLINT,
    estado_recomendacion VARCHAR(20) NOT NULL DEFAULT 'PENDIENTE',
    responsable_revision VARCHAR(150),
    fecha_revision TIMESTAMP,
    observaciones TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_recomendaciones_hotspot
        FOREIGN KEY (id_hotspot)
        REFERENCES hotspots (id_hotspot),
    CONSTRAINT fk_recomendaciones_zona
        FOREIGN KEY (id_zona)
        REFERENCES zonas_operativas (id_zona),
    CONSTRAINT fk_recomendaciones_comisaria
        FOREIGN KEY (id_comisaria)
        REFERENCES comisarias (id_comisaria),
    CONSTRAINT chk_recomendaciones_turno
        CHECK (turno IN ('MANANA', 'TARDE', 'NOCHE', 'MADRUGADA')),
    CONSTRAINT chk_recomendaciones_prioridad
        CHECK (prioridad IN ('BAJA', 'MEDIA', 'ALTA', 'CRITICA')),
    CONSTRAINT chk_recomendaciones_tipo
        CHECK (
            tipo_recomendacion IN (
                'PATRULLAJE_PREVENTIVO',
                'PATRULLAJE_DISUASIVO',
                'INTERVENCION_FOCALIZADA',
                'CONTROL_DE_ACCESOS',
                'VIGILANCIA_ENCUBIERTA'
            )
        ),
    CONSTRAINT chk_recomendaciones_estado
        CHECK (estado_recomendacion IN ('PENDIENTE', 'APROBADA', 'EJECUTADA', 'DESCARTADA')),
    CONSTRAINT chk_recomendaciones_efectivos
        CHECK (cantidad_efectivos IS NULL OR cantidad_efectivos >= 0),
    CONSTRAINT chk_recomendaciones_unidades
        CHECK (cantidad_unidades IS NULL OR cantidad_unidades >= 0)
);

CREATE INDEX IF NOT EXISTS idx_recomendaciones_fecha_operativa
    ON recomendaciones_patrullaje (fecha_operativa);

CREATE INDEX IF NOT EXISTS idx_recomendaciones_turno
    ON recomendaciones_patrullaje (turno);

CREATE INDEX IF NOT EXISTS idx_recomendaciones_prioridad
    ON recomendaciones_patrullaje (prioridad);

CREATE INDEX IF NOT EXISTS idx_recomendaciones_distrito
    ON recomendaciones_patrullaje (distrito);

CREATE INDEX IF NOT EXISTS idx_recomendaciones_estado
    ON recomendaciones_patrullaje (estado_recomendacion);

CREATE INDEX IF NOT EXISTS idx_recomendaciones_hotspot
    ON recomendaciones_patrullaje (id_hotspot);

CREATE INDEX IF NOT EXISTS idx_recomendaciones_zona
    ON recomendaciones_patrullaje (id_zona);

CREATE INDEX IF NOT EXISTS idx_recomendaciones_comisaria
    ON recomendaciones_patrullaje (id_comisaria);
