\connect siged_pnp;

CREATE TABLE IF NOT EXISTS auth_roles (
    codigo VARCHAR(30) PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    descripcion VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS auth_usuarios (
    id_usuario BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(80) NOT NULL,
    nombre_completo VARCHAR(150) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    rol_codigo VARCHAR(30) NOT NULL,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    ultimo_login TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_auth_usuarios_rol
        FOREIGN KEY (rol_codigo)
        REFERENCES auth_roles (codigo)
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_auth_usuarios_username_lower
    ON auth_usuarios (LOWER(username));

CREATE INDEX IF NOT EXISTS idx_auth_usuarios_rol_codigo
    ON auth_usuarios (rol_codigo);

CREATE INDEX IF NOT EXISTS idx_auth_usuarios_activo
    ON auth_usuarios (activo);

INSERT INTO auth_roles (codigo, nombre, descripcion)
VALUES
    ('admin', 'Administrador', 'Gestiona usuarios, administracion y configuracion operativa.'),
    ('analista', 'Analista', 'Consulta datos, analitica y endpoints operativos de carga.'),
    ('consulta', 'Consulta', 'Accede a consultas y visualizacion sin permisos administrativos.')
ON CONFLICT (codigo) DO UPDATE
SET
    nombre = EXCLUDED.nombre,
    descripcion = EXCLUDED.descripcion;
