-- archivo: database/sql/13_dim_territorio.sql
\connect siged_pnp;

CREATE OR REPLACE FUNCTION siged_normalize_name(input_text TEXT)
RETURNS VARCHAR(150)
LANGUAGE sql
IMMUTABLE
AS $$
    SELECT NULLIF(UPPER(REGEXP_REPLACE(BTRIM(COALESCE(input_text, '')), '\s+', ' ', 'g')), '');
$$;

CREATE OR REPLACE FUNCTION siged_slug(input_text TEXT)
RETURNS VARCHAR(150)
LANGUAGE sql
IMMUTABLE
AS $$
    SELECT COALESCE(NULLIF(REGEXP_REPLACE(COALESCE(siged_normalize_name(input_text), ''), '[^A-Z0-9]+', '_', 'g'), ''), 'SIN_DATO');
$$;

CREATE TABLE IF NOT EXISTS dim_territorios (
    id_territorio BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo_territorio VARCHAR(60) NOT NULL,
    nombre_territorio VARCHAR(150) NOT NULL,
    nombre_normalizado VARCHAR(150) NOT NULL,
    tipo_territorio VARCHAR(30) NOT NULL,
    id_territorio_padre BIGINT,
    nivel_jerarquia SMALLINT NOT NULL,
    codigo_referencia VARCHAR(40),
    estado_territorio VARCHAR(20) NOT NULL DEFAULT 'ACTIVO',
    metadata JSONB NOT NULL DEFAULT '{}'::JSONB,
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_dim_territorios_codigo
        UNIQUE (codigo_territorio),
    CONSTRAINT fk_dim_territorios_padre
        FOREIGN KEY (id_territorio_padre)
        REFERENCES dim_territorios (id_territorio),
    CONSTRAINT chk_dim_territorios_tipo
        CHECK (
            tipo_territorio IN (
                'PAIS',
                'DEPARTAMENTO',
                'PROVINCIA',
                'DISTRITO',
                'JURISDICCION_POLICIAL',
                'COMISARIA',
                'ZONA_OPERATIVA',
                'SECTOR'
            )
        ),
    CONSTRAINT chk_dim_territorios_estado
        CHECK (estado_territorio IN ('ACTIVO', 'INACTIVO'))
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_dim_territorios_tipo_nombre_padre
    ON dim_territorios (
        tipo_territorio,
        nombre_normalizado,
        COALESCE(id_territorio_padre, 0)
    );

CREATE INDEX IF NOT EXISTS idx_dim_territorios_tipo
    ON dim_territorios (tipo_territorio);

CREATE INDEX IF NOT EXISTS idx_dim_territorios_padre
    ON dim_territorios (id_territorio_padre);

CREATE TABLE IF NOT EXISTS territorio_aliases (
    id_alias BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    alias_texto VARCHAR(150) NOT NULL,
    alias_normalizado VARCHAR(150) NOT NULL,
    id_territorio BIGINT NOT NULL,
    tipo_alias VARCHAR(20) NOT NULL DEFAULT 'OFICIAL',
    es_preferido BOOLEAN NOT NULL DEFAULT TRUE,
    metadata JSONB NOT NULL DEFAULT '{}'::JSONB,
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_territorio_aliases_territorio
        FOREIGN KEY (id_territorio)
        REFERENCES dim_territorios (id_territorio),
    CONSTRAINT chk_territorio_aliases_tipo
        CHECK (tipo_alias IN ('OFICIAL', 'OPERATIVO', 'MIGRACION'))
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_territorio_aliases_valor_territorio
    ON territorio_aliases (alias_normalizado, id_territorio);

CREATE INDEX IF NOT EXISTS idx_territorio_aliases_normalizado
    ON territorio_aliases (alias_normalizado);

ALTER TABLE comisarias
    ADD COLUMN IF NOT EXISTS distrito_normalizado VARCHAR(100),
    ADD COLUMN IF NOT EXISTS id_territorio BIGINT,
    ADD COLUMN IF NOT EXISTS id_territorio_distrito BIGINT;

ALTER TABLE eventos_delictivos
    ADD COLUMN IF NOT EXISTS distrito_normalizado VARCHAR(100),
    ADD COLUMN IF NOT EXISTS id_territorio_distrito BIGINT;

ALTER TABLE zonas_operativas
    ADD COLUMN IF NOT EXISTS distrito_normalizado VARCHAR(100),
    ADD COLUMN IF NOT EXISTS id_territorio BIGINT,
    ADD COLUMN IF NOT EXISTS id_territorio_distrito BIGINT;

ALTER TABLE hotspots
    ADD COLUMN IF NOT EXISTS distrito_normalizado VARCHAR(100),
    ADD COLUMN IF NOT EXISTS id_territorio_distrito BIGINT;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'fk_comisarias_territorio'
    ) THEN
        ALTER TABLE comisarias
            ADD CONSTRAINT fk_comisarias_territorio
            FOREIGN KEY (id_territorio)
            REFERENCES dim_territorios (id_territorio);
    END IF;

    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'fk_comisarias_territorio_distrito'
    ) THEN
        ALTER TABLE comisarias
            ADD CONSTRAINT fk_comisarias_territorio_distrito
            FOREIGN KEY (id_territorio_distrito)
            REFERENCES dim_territorios (id_territorio);
    END IF;

    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'fk_eventos_territorio_distrito'
    ) THEN
        ALTER TABLE eventos_delictivos
            ADD CONSTRAINT fk_eventos_territorio_distrito
            FOREIGN KEY (id_territorio_distrito)
            REFERENCES dim_territorios (id_territorio);
    END IF;

    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'fk_zonas_territorio'
    ) THEN
        ALTER TABLE zonas_operativas
            ADD CONSTRAINT fk_zonas_territorio
            FOREIGN KEY (id_territorio)
            REFERENCES dim_territorios (id_territorio);
    END IF;

    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'fk_zonas_territorio_distrito'
    ) THEN
        ALTER TABLE zonas_operativas
            ADD CONSTRAINT fk_zonas_territorio_distrito
            FOREIGN KEY (id_territorio_distrito)
            REFERENCES dim_territorios (id_territorio);
    END IF;

    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'fk_hotspots_territorio_distrito'
    ) THEN
        ALTER TABLE hotspots
            ADD CONSTRAINT fk_hotspots_territorio_distrito
            FOREIGN KEY (id_territorio_distrito)
            REFERENCES dim_territorios (id_territorio);
    END IF;
END $$;

CREATE OR REPLACE FUNCTION siged_upsert_territorio(
    p_codigo_territorio TEXT,
    p_nombre_territorio TEXT,
    p_tipo_territorio TEXT,
    p_id_territorio_padre BIGINT,
    p_nivel_jerarquia SMALLINT,
    p_codigo_referencia TEXT DEFAULT NULL,
    p_metadata JSONB DEFAULT '{}'::JSONB
)
RETURNS BIGINT
LANGUAGE plpgsql
AS $$
DECLARE
    v_id_territorio BIGINT;
BEGIN
    INSERT INTO dim_territorios (
        codigo_territorio,
        nombre_territorio,
        nombre_normalizado,
        tipo_territorio,
        id_territorio_padre,
        nivel_jerarquia,
        codigo_referencia,
        metadata,
        updated_at
    ) VALUES (
        p_codigo_territorio,
        COALESCE(siged_normalize_name(p_nombre_territorio), 'SIN DATO'),
        COALESCE(siged_normalize_name(p_nombre_territorio), 'SIN DATO'),
        p_tipo_territorio,
        p_id_territorio_padre,
        p_nivel_jerarquia,
        NULLIF(BTRIM(COALESCE(p_codigo_referencia, '')), ''),
        COALESCE(p_metadata, '{}'::JSONB),
        NOW()
    )
    ON CONFLICT (codigo_territorio) DO UPDATE
    SET
        nombre_territorio = EXCLUDED.nombre_territorio,
        nombre_normalizado = EXCLUDED.nombre_normalizado,
        tipo_territorio = EXCLUDED.tipo_territorio,
        id_territorio_padre = EXCLUDED.id_territorio_padre,
        nivel_jerarquia = EXCLUDED.nivel_jerarquia,
        codigo_referencia = EXCLUDED.codigo_referencia,
        metadata = COALESCE(dim_territorios.metadata, '{}'::JSONB) || COALESCE(EXCLUDED.metadata, '{}'::JSONB),
        updated_at = NOW()
    RETURNING id_territorio
    INTO v_id_territorio;

    RETURN v_id_territorio;
END;
$$;

CREATE OR REPLACE FUNCTION siged_resolve_territory_alias(p_alias TEXT)
RETURNS BIGINT
LANGUAGE sql
STABLE
AS $$
    SELECT ta.id_territorio
    FROM territorio_aliases ta
    WHERE ta.alias_normalizado = siged_normalize_name(p_alias)
    ORDER BY ta.es_preferido DESC, ta.id_alias ASC
    LIMIT 1;
$$;

CREATE OR REPLACE FUNCTION siged_refresh_territorial_dimension()
RETURNS VOID
LANGUAGE plpgsql
AS $$
DECLARE
    v_pais BIGINT;
    v_departamento_nd BIGINT;
    v_provincia_nd BIGINT;
BEGIN
    UPDATE comisarias
    SET distrito_normalizado = siged_normalize_name(distrito)
    WHERE distrito_normalizado IS DISTINCT FROM siged_normalize_name(distrito);

    UPDATE eventos_delictivos
    SET distrito_normalizado = siged_normalize_name(distrito)
    WHERE distrito_normalizado IS DISTINCT FROM siged_normalize_name(distrito);

    UPDATE zonas_operativas
    SET distrito_normalizado = siged_normalize_name(distrito)
    WHERE distrito_normalizado IS DISTINCT FROM siged_normalize_name(distrito);

    UPDATE hotspots
    SET distrito_normalizado = siged_normalize_name(distrito)
    WHERE distrito_normalizado IS DISTINCT FROM siged_normalize_name(distrito);

    v_pais := siged_upsert_territorio(
        'PAIS-PERU',
        'PERU',
        'PAIS',
        NULL::BIGINT,
        0::SMALLINT,
        'PE',
        jsonb_build_object('fuente', 'bootstrap')
    );

    v_departamento_nd := siged_upsert_territorio(
        'DEP-NO_DEFINIDO',
        'NO DEFINIDO',
        'DEPARTAMENTO',
        v_pais,
        1::SMALLINT,
        'ND',
        jsonb_build_object('fuente', 'bootstrap')
    );

    v_provincia_nd := siged_upsert_territorio(
        'PROV-NO_DEFINIDA',
        'NO DEFINIDA',
        'PROVINCIA',
        v_departamento_nd,
        2::SMALLINT,
        'ND',
        jsonb_build_object('fuente', 'bootstrap')
    );

    INSERT INTO dim_territorios (
        codigo_territorio,
        nombre_territorio,
        nombre_normalizado,
        tipo_territorio,
        id_territorio_padre,
        nivel_jerarquia,
        codigo_referencia,
        metadata,
        updated_at
    )
    SELECT DISTINCT
        'DIST-' || siged_slug(src.distrito_normalizado) AS codigo_territorio,
        src.distrito_normalizado AS nombre_territorio,
        src.distrito_normalizado AS nombre_normalizado,
        'DISTRITO' AS tipo_territorio,
        v_provincia_nd AS id_territorio_padre,
        3 AS nivel_jerarquia,
        src.distrito_normalizado AS codigo_referencia,
        jsonb_build_object('fuente', 'migracion_incremental') AS metadata,
        NOW() AS updated_at
    FROM (
        SELECT distrito_normalizado
        FROM comisarias
        WHERE distrito_normalizado IS NOT NULL
        UNION
        SELECT distrito_normalizado
        FROM eventos_delictivos
        WHERE distrito_normalizado IS NOT NULL
        UNION
        SELECT distrito_normalizado
        FROM zonas_operativas
        WHERE distrito_normalizado IS NOT NULL
        UNION
        SELECT distrito_normalizado
        FROM hotspots
        WHERE distrito_normalizado IS NOT NULL
    ) src
    ON CONFLICT (codigo_territorio) DO UPDATE
    SET
        nombre_territorio = EXCLUDED.nombre_territorio,
        nombre_normalizado = EXCLUDED.nombre_normalizado,
        id_territorio_padre = EXCLUDED.id_territorio_padre,
        metadata = COALESCE(dim_territorios.metadata, '{}'::JSONB) || COALESCE(EXCLUDED.metadata, '{}'::JSONB),
        updated_at = NOW();

    INSERT INTO territorio_aliases (
        alias_texto,
        alias_normalizado,
        id_territorio,
        tipo_alias,
        es_preferido,
        metadata,
        updated_at
    )
    SELECT
        MIN(src.alias_texto) AS alias_texto,
        src.alias_normalizado,
        dt.id_territorio,
        'MIGRACION' AS tipo_alias,
        TRUE AS es_preferido,
        jsonb_build_object(
            'fuentes',
            jsonb_agg(DISTINCT src.fuente_alias ORDER BY src.fuente_alias)
        ) AS metadata,
        NOW() AS updated_at
    FROM (
        SELECT distrito AS alias_texto, distrito_normalizado AS alias_normalizado, 'comisarias' AS fuente_alias
        FROM comisarias
        WHERE distrito_normalizado IS NOT NULL
        UNION
        SELECT distrito AS alias_texto, distrito_normalizado AS alias_normalizado, 'eventos_delictivos' AS fuente_alias
        FROM eventos_delictivos
        WHERE distrito_normalizado IS NOT NULL
        UNION
        SELECT distrito AS alias_texto, distrito_normalizado AS alias_normalizado, 'zonas_operativas' AS fuente_alias
        FROM zonas_operativas
        WHERE distrito_normalizado IS NOT NULL
        UNION
        SELECT distrito AS alias_texto, distrito_normalizado AS alias_normalizado, 'hotspots' AS fuente_alias
        FROM hotspots
        WHERE distrito_normalizado IS NOT NULL
    ) src
    INNER JOIN dim_territorios dt
        ON dt.codigo_territorio = 'DIST-' || siged_slug(src.alias_normalizado)
    GROUP BY
        src.alias_normalizado,
        dt.id_territorio
    ON CONFLICT (alias_normalizado, id_territorio) DO UPDATE
    SET
        alias_texto = EXCLUDED.alias_texto,
        metadata = COALESCE(territorio_aliases.metadata, '{}'::JSONB) || COALESCE(EXCLUDED.metadata, '{}'::JSONB),
        updated_at = NOW();

    INSERT INTO dim_territorios (
        codigo_territorio,
        nombre_territorio,
        nombre_normalizado,
        tipo_territorio,
        id_territorio_padre,
        nivel_jerarquia,
        codigo_referencia,
        metadata,
        updated_at
    )
    SELECT
        'COM-' || src.id_comisaria::TEXT AS codigo_territorio,
        src.nombre_dimension AS nombre_territorio,
        src.nombre_dimension AS nombre_normalizado,
        'COMISARIA' AS tipo_territorio,
        src.id_territorio_padre,
        4 AS nivel_jerarquia,
        src.id_comisaria::TEXT AS codigo_referencia,
        jsonb_strip_nulls(
            jsonb_build_object(
                'id_comisaria', src.id_comisaria,
                'direccion', src.direccion,
                'distrito', src.distrito_normalizado
            )
        ) AS metadata,
        NOW() AS updated_at
    FROM (
        SELECT
            c.id_comisaria,
            c.direccion,
            c.distrito_normalizado,
            COALESCE(siged_resolve_territory_alias(c.distrito), v_provincia_nd) AS id_territorio_padre,
            CASE
                WHEN COUNT(*) OVER (
                    PARTITION BY
                        siged_normalize_name(c.nombre_comisaria),
                        COALESCE(siged_resolve_territory_alias(c.distrito), v_provincia_nd)
                ) > 1
                THEN (
                    siged_normalize_name(c.nombre_comisaria)
                    || ' ['
                    || COALESCE(NULLIF(BTRIM(c.codigo_cpnp), ''), c.id_comisaria::TEXT)
                    || ']'
                )
                ELSE siged_normalize_name(c.nombre_comisaria)
            END AS nombre_dimension
        FROM comisarias c
    ) src
    ON CONFLICT (codigo_territorio) DO UPDATE
    SET
        nombre_territorio = EXCLUDED.nombre_territorio,
        nombre_normalizado = EXCLUDED.nombre_normalizado,
        tipo_territorio = EXCLUDED.tipo_territorio,
        id_territorio_padre = EXCLUDED.id_territorio_padre,
        nivel_jerarquia = EXCLUDED.nivel_jerarquia,
        codigo_referencia = EXCLUDED.codigo_referencia,
        metadata = COALESCE(dim_territorios.metadata, '{}'::JSONB) || COALESCE(EXCLUDED.metadata, '{}'::JSONB),
        updated_at = NOW();

    INSERT INTO dim_territorios (
        codigo_territorio,
        nombre_territorio,
        nombre_normalizado,
        tipo_territorio,
        id_territorio_padre,
        nivel_jerarquia,
        codigo_referencia,
        metadata,
        updated_at
    )
    SELECT
        'ZONA-' || z.id_zona::TEXT AS codigo_territorio,
        siged_normalize_name(z.nombre_zona) AS nombre_territorio,
        siged_normalize_name(z.nombre_zona) AS nombre_normalizado,
        CASE
            WHEN z.tipo_zona = 'JURISDICCION' THEN 'JURISDICCION_POLICIAL'
            WHEN z.tipo_zona = 'SECTOR' THEN 'SECTOR'
            ELSE 'ZONA_OPERATIVA'
        END AS tipo_territorio,
        COALESCE(
            (
                SELECT dt.id_territorio
                FROM dim_territorios dt
                WHERE dt.codigo_territorio = 'COM-' || z.id_comisaria::TEXT
                LIMIT 1
            ),
            siged_resolve_territory_alias(z.distrito),
            v_provincia_nd
        ) AS id_territorio_padre,
        CASE
            WHEN z.tipo_zona = 'JURISDICCION' THEN 4
            ELSE 5
        END AS nivel_jerarquia,
        COALESCE(NULLIF(BTRIM(z.codigo_zona), ''), z.id_zona::TEXT) AS codigo_referencia,
        jsonb_strip_nulls(
            jsonb_build_object(
                'id_zona', z.id_zona,
                'tipo_zona', z.tipo_zona,
                'estado_zona', z.estado_zona,
                'prioridad_operativa', z.prioridad_operativa,
                'id_comisaria', z.id_comisaria,
                'distrito', z.distrito_normalizado
            )
        ) AS metadata,
        NOW() AS updated_at
    FROM zonas_operativas z
    ON CONFLICT (codigo_territorio) DO UPDATE
    SET
        nombre_territorio = EXCLUDED.nombre_territorio,
        nombre_normalizado = EXCLUDED.nombre_normalizado,
        tipo_territorio = EXCLUDED.tipo_territorio,
        id_territorio_padre = EXCLUDED.id_territorio_padre,
        nivel_jerarquia = EXCLUDED.nivel_jerarquia,
        codigo_referencia = EXCLUDED.codigo_referencia,
        metadata = COALESCE(dim_territorios.metadata, '{}'::JSONB) || COALESCE(EXCLUDED.metadata, '{}'::JSONB),
        updated_at = NOW();

    UPDATE comisarias
    SET
        id_territorio_distrito = siged_resolve_territory_alias(distrito),
        distrito_normalizado = siged_normalize_name(distrito);

    UPDATE comisarias c
    SET id_territorio = dt.id_territorio
    FROM dim_territorios dt
    WHERE dt.codigo_territorio = 'COM-' || c.id_comisaria::TEXT
      AND c.id_territorio IS DISTINCT FROM dt.id_territorio;

    UPDATE zonas_operativas
    SET
        id_territorio_distrito = COALESCE(
            (
                SELECT c.id_territorio_distrito
                FROM comisarias c
                WHERE c.id_comisaria = zonas_operativas.id_comisaria
                LIMIT 1
            ),
            siged_resolve_territory_alias(distrito)
        ),
        distrito_normalizado = siged_normalize_name(distrito);

    UPDATE zonas_operativas z
    SET id_territorio = dt.id_territorio
    FROM dim_territorios dt
    WHERE dt.codigo_territorio = 'ZONA-' || z.id_zona::TEXT
      AND z.id_territorio IS DISTINCT FROM dt.id_territorio;

    UPDATE eventos_delictivos
    SET
        id_territorio_distrito = COALESCE(
            (
                SELECT c.id_territorio_distrito
                FROM comisarias c
                WHERE c.id_comisaria = eventos_delictivos.id_comisaria
                LIMIT 1
            ),
            siged_resolve_territory_alias(distrito)
        ),
        distrito_normalizado = siged_normalize_name(distrito);

    UPDATE eventos_delictivos e
    SET
        distrito = dt.nombre_territorio,
        distrito_normalizado = dt.nombre_normalizado
    FROM dim_territorios dt
    WHERE dt.id_territorio = e.id_territorio_distrito
      AND (
        e.distrito IS DISTINCT FROM dt.nombre_territorio
        OR e.distrito_normalizado IS DISTINCT FROM dt.nombre_normalizado
      );

    UPDATE hotspots
    SET
        id_territorio_distrito = COALESCE(
            (
                SELECT z.id_territorio_distrito
                FROM zonas_operativas z
                WHERE z.id_zona = hotspots.id_zona
                LIMIT 1
            ),
            siged_resolve_territory_alias(distrito)
        ),
        distrito_normalizado = siged_normalize_name(distrito);

    UPDATE hotspots h
    SET
        distrito = dt.nombre_territorio,
        distrito_normalizado = dt.nombre_normalizado
    FROM dim_territorios dt
    WHERE dt.id_territorio = h.id_territorio_distrito
      AND (
        h.distrito IS DISTINCT FROM dt.nombre_territorio
        OR h.distrito_normalizado IS DISTINCT FROM dt.nombre_normalizado
      );
END;
$$;

CREATE OR REPLACE FUNCTION siged_apply_district_normalization()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
    v_distrito_id BIGINT;
    v_nombre_canonico VARCHAR(150);
BEGIN
    IF NEW.distrito IS NULL THEN
        RETURN NEW;
    END IF;

    NEW.distrito_normalizado := siged_normalize_name(NEW.distrito);
    v_distrito_id := siged_resolve_territory_alias(NEW.distrito);

    IF v_distrito_id IS NOT NULL THEN
        NEW.id_territorio_distrito := v_distrito_id;

        SELECT nombre_territorio
        INTO v_nombre_canonico
        FROM dim_territorios
        WHERE id_territorio = v_distrito_id
        LIMIT 1;

        IF v_nombre_canonico IS NOT NULL THEN
            NEW.distrito := v_nombre_canonico;
            NEW.distrito_normalizado := siged_normalize_name(v_nombre_canonico);
        END IF;
    END IF;

    RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION siged_validate_territorial_consistency()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
    v_new_data JSONB;
    v_comisaria_distrito_id BIGINT;
    v_zona_distrito_id BIGINT;
    v_id_comisaria BIGINT;
    v_id_zona BIGINT;
    v_id_territorio_distrito BIGINT;
BEGIN
    v_new_data := to_jsonb(NEW);
    v_id_comisaria := NULLIF(v_new_data ->> 'id_comisaria', '')::BIGINT;
    v_id_zona := NULLIF(v_new_data ->> 'id_zona', '')::BIGINT;
    v_id_territorio_distrito := NULLIF(v_new_data ->> 'id_territorio_distrito', '')::BIGINT;

    IF TG_TABLE_NAME = 'eventos_delictivos' THEN
        IF v_id_comisaria IS NOT NULL THEN
            SELECT c.id_territorio_distrito
            INTO v_comisaria_distrito_id
            FROM comisarias c
            WHERE c.id_comisaria = v_id_comisaria
            LIMIT 1;

            IF v_comisaria_distrito_id IS NOT NULL THEN
                IF v_id_territorio_distrito IS NULL THEN
                    NEW.id_territorio_distrito := v_comisaria_distrito_id;
                ELSIF v_id_territorio_distrito <> v_comisaria_distrito_id THEN
                    RAISE EXCEPTION 'El distrito del evento no coincide con la comisaria %', v_id_comisaria;
                END IF;
            END IF;
        END IF;
    ELSIF TG_TABLE_NAME = 'zonas_operativas' THEN
        IF v_id_comisaria IS NOT NULL THEN
            SELECT c.id_territorio_distrito
            INTO v_comisaria_distrito_id
            FROM comisarias c
            WHERE c.id_comisaria = v_id_comisaria
            LIMIT 1;

            IF v_comisaria_distrito_id IS NOT NULL
               AND v_id_territorio_distrito IS NOT NULL
               AND v_id_territorio_distrito <> v_comisaria_distrito_id THEN
                RAISE EXCEPTION 'La zona operativa no coincide con el distrito de la comisaria %', v_id_comisaria;
            END IF;
        END IF;
    ELSIF TG_TABLE_NAME = 'hotspots' THEN
        IF v_id_zona IS NOT NULL THEN
            SELECT z.id_territorio_distrito
            INTO v_zona_distrito_id
            FROM zonas_operativas z
            WHERE z.id_zona = v_id_zona
            LIMIT 1;

            IF v_zona_distrito_id IS NOT NULL THEN
                IF v_id_territorio_distrito IS NULL THEN
                    NEW.id_territorio_distrito := v_zona_distrito_id;
                ELSIF v_id_territorio_distrito <> v_zona_distrito_id THEN
                    RAISE EXCEPTION 'El distrito del hotspot no coincide con la zona %', v_id_zona;
                END IF;
            END IF;
        END IF;
    END IF;

    RETURN NEW;
END;
$$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_trigger WHERE tgname = 'trg_comisarias_distrito_normalizado'
    ) THEN
        CREATE TRIGGER trg_comisarias_distrito_normalizado
        BEFORE INSERT OR UPDATE OF distrito
        ON comisarias
        FOR EACH ROW
        EXECUTE FUNCTION siged_apply_district_normalization();
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_trigger WHERE tgname = 'trg_eventos_distrito_normalizado'
    ) THEN
        CREATE TRIGGER trg_eventos_distrito_normalizado
        BEFORE INSERT OR UPDATE OF distrito, id_comisaria
        ON eventos_delictivos
        FOR EACH ROW
        EXECUTE FUNCTION siged_apply_district_normalization();
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_trigger WHERE tgname = 'trg_zonas_distrito_normalizado'
    ) THEN
        CREATE TRIGGER trg_zonas_distrito_normalizado
        BEFORE INSERT OR UPDATE OF distrito
        ON zonas_operativas
        FOR EACH ROW
        EXECUTE FUNCTION siged_apply_district_normalization();
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_trigger WHERE tgname = 'trg_hotspots_distrito_normalizado'
    ) THEN
        CREATE TRIGGER trg_hotspots_distrito_normalizado
        BEFORE INSERT OR UPDATE OF distrito, id_zona
        ON hotspots
        FOR EACH ROW
        EXECUTE FUNCTION siged_apply_district_normalization();
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_trigger WHERE tgname = 'trg_eventos_validacion_territorial'
    ) THEN
        CREATE TRIGGER trg_eventos_validacion_territorial
        BEFORE INSERT OR UPDATE OF distrito, id_comisaria
        ON eventos_delictivos
        FOR EACH ROW
        EXECUTE FUNCTION siged_validate_territorial_consistency();
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_trigger WHERE tgname = 'trg_zonas_validacion_territorial'
    ) THEN
        CREATE TRIGGER trg_zonas_validacion_territorial
        BEFORE INSERT OR UPDATE OF distrito, id_comisaria
        ON zonas_operativas
        FOR EACH ROW
        EXECUTE FUNCTION siged_validate_territorial_consistency();
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_trigger WHERE tgname = 'trg_hotspots_validacion_territorial'
    ) THEN
        CREATE TRIGGER trg_hotspots_validacion_territorial
        BEFORE INSERT OR UPDATE OF distrito, id_zona
        ON hotspots
        FOR EACH ROW
        EXECUTE FUNCTION siged_validate_territorial_consistency();
    END IF;
END $$;

CREATE OR REPLACE VIEW vw_territorial_inconsistencias AS
SELECT
    'EVENTO_COMISARIA' AS tipo_inconsistencia,
    e.id_evento::TEXT AS referencia,
    e.distrito AS distrito_registro,
    c.distrito AS distrito_referencia,
    e.id_comisaria::TEXT AS referencia_relacionada,
    e.id_territorio_distrito AS id_territorio_registro,
    c.id_territorio_distrito AS id_territorio_referencia
FROM eventos_delictivos e
INNER JOIN comisarias c
    ON c.id_comisaria = e.id_comisaria
WHERE e.id_comisaria IS NOT NULL
  AND e.id_territorio_distrito IS DISTINCT FROM c.id_territorio_distrito

UNION ALL

SELECT
    'ZONA_COMISARIA' AS tipo_inconsistencia,
    z.id_zona::TEXT AS referencia,
    z.distrito AS distrito_registro,
    c.distrito AS distrito_referencia,
    z.id_comisaria::TEXT AS referencia_relacionada,
    z.id_territorio_distrito AS id_territorio_registro,
    c.id_territorio_distrito AS id_territorio_referencia
FROM zonas_operativas z
INNER JOIN comisarias c
    ON c.id_comisaria = z.id_comisaria
WHERE z.id_comisaria IS NOT NULL
  AND z.id_territorio_distrito IS DISTINCT FROM c.id_territorio_distrito

UNION ALL

SELECT
    'HOTSPOT_ZONA' AS tipo_inconsistencia,
    h.id_hotspot::TEXT AS referencia,
    h.distrito AS distrito_registro,
    z.distrito AS distrito_referencia,
    h.id_zona::TEXT AS referencia_relacionada,
    h.id_territorio_distrito AS id_territorio_registro,
    z.id_territorio_distrito AS id_territorio_referencia
FROM hotspots h
INNER JOIN zonas_operativas z
    ON z.id_zona = h.id_zona
WHERE h.id_zona IS NOT NULL
  AND h.id_territorio_distrito IS DISTINCT FROM z.id_territorio_distrito;

SELECT siged_refresh_territorial_dimension();
