\connect siged_pnp;

CREATE TABLE IF NOT EXISTS territorio_regiones (
    id_region BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_objectid BIGINT,
    codigo_region VARCHAR(20) NOT NULL,
    nombre_region VARCHAR(120) NOT NULL,
    nombre_normalizado VARCHAR(120) NOT NULL,
    macroregion_codigo VARCHAR(20),
    macroregion_nombre VARCHAR(120),
    area_km2 NUMERIC(16,6),
    perimetro_km NUMERIC(16,6),
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    source_properties JSONB NOT NULL DEFAULT '{}'::JSONB,
    geom geometry(MultiPolygon, 4326) NOT NULL,
    geom_simplified geometry(MultiPolygon, 4326),
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_territorio_regiones_codigo UNIQUE (codigo_region),
    CONSTRAINT uq_territorio_regiones_objectid UNIQUE (source_objectid)
);

CREATE INDEX IF NOT EXISTS idx_territorio_regiones_nombre
    ON territorio_regiones (nombre_normalizado);

CREATE INDEX IF NOT EXISTS idx_territorio_regiones_activo
    ON territorio_regiones (activo);

CREATE INDEX IF NOT EXISTS idx_territorio_regiones_geom_gist
    ON territorio_regiones
    USING GIST (geom);

CREATE INDEX IF NOT EXISTS idx_territorio_regiones_geom_simplified_gist
    ON territorio_regiones
    USING GIST (geom_simplified);


CREATE TABLE IF NOT EXISTS territorio_divisiones (
    id_division BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_region BIGINT NOT NULL,
    source_objectid BIGINT,
    codigo_division VARCHAR(20) NOT NULL,
    nombre_division VARCHAR(150) NOT NULL,
    nombre_normalizado VARCHAR(150) NOT NULL,
    area_km2 NUMERIC(16,6),
    perimetro_km NUMERIC(16,6),
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    source_properties JSONB NOT NULL DEFAULT '{}'::JSONB,
    geom geometry(MultiPolygon, 4326) NOT NULL,
    geom_simplified geometry(MultiPolygon, 4326),
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_territorio_divisiones_codigo UNIQUE (codigo_division),
    CONSTRAINT uq_territorio_divisiones_objectid UNIQUE (source_objectid),
    CONSTRAINT fk_territorio_divisiones_region
        FOREIGN KEY (id_region)
        REFERENCES territorio_regiones (id_region)
);

CREATE INDEX IF NOT EXISTS idx_territorio_divisiones_region
    ON territorio_divisiones (id_region);

CREATE INDEX IF NOT EXISTS idx_territorio_divisiones_nombre
    ON territorio_divisiones (nombre_normalizado);

CREATE INDEX IF NOT EXISTS idx_territorio_divisiones_activo
    ON territorio_divisiones (activo);

CREATE INDEX IF NOT EXISTS idx_territorio_divisiones_geom_gist
    ON territorio_divisiones
    USING GIST (geom);

CREATE INDEX IF NOT EXISTS idx_territorio_divisiones_geom_simplified_gist
    ON territorio_divisiones
    USING GIST (geom_simplified);


CREATE TABLE IF NOT EXISTS territorio_comisarias (
    id_territorio_comisaria BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_region BIGINT NOT NULL,
    id_division BIGINT NOT NULL,
    source_objectid BIGINT,
    codigo_cpnp VARCHAR(20) NOT NULL,
    codigo_unidad VARCHAR(20),
    nombre_comisaria VARCHAR(150) NOT NULL,
    nombre_normalizado VARCHAR(150) NOT NULL,
    tipo_comisaria VARCHAR(20),
    codigo_inei VARCHAR(20),
    departamento VARCHAR(120),
    provincia VARCHAR(120),
    distrito VARCHAR(120),
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    source_properties JSONB NOT NULL DEFAULT '{}'::JSONB,
    geom geometry(Point, 4326) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_territorio_comisarias_codigo UNIQUE (codigo_cpnp),
    CONSTRAINT uq_territorio_comisarias_objectid UNIQUE (source_objectid),
    CONSTRAINT fk_territorio_comisarias_region
        FOREIGN KEY (id_region)
        REFERENCES territorio_regiones (id_region),
    CONSTRAINT fk_territorio_comisarias_division
        FOREIGN KEY (id_division)
        REFERENCES territorio_divisiones (id_division)
);

CREATE INDEX IF NOT EXISTS idx_territorio_comisarias_region
    ON territorio_comisarias (id_region);

CREATE INDEX IF NOT EXISTS idx_territorio_comisarias_division
    ON territorio_comisarias (id_division);

CREATE INDEX IF NOT EXISTS idx_territorio_comisarias_nombre
    ON territorio_comisarias (nombre_normalizado);

CREATE INDEX IF NOT EXISTS idx_territorio_comisarias_activo
    ON territorio_comisarias (activo);

CREATE INDEX IF NOT EXISTS idx_territorio_comisarias_geom_gist
    ON territorio_comisarias
    USING GIST (geom);


CREATE TABLE IF NOT EXISTS territorio_jurisdicciones (
    id_jurisdiccion BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_region BIGINT NOT NULL,
    id_division BIGINT NOT NULL,
    id_territorio_comisaria BIGINT NOT NULL,
    source_objectid BIGINT,
    codigo_jurisdiccion VARCHAR(40) NOT NULL,
    nombre_jurisdiccion VARCHAR(150) NOT NULL,
    nombre_normalizado VARCHAR(150) NOT NULL,
    tipo_cobertura VARCHAR(50),
    codigo_inei VARCHAR(20),
    codigo_unidad VARCHAR(20),
    sectores_referencia VARCHAR(50),
    area_km2 NUMERIC(16,6),
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    source_properties JSONB NOT NULL DEFAULT '{}'::JSONB,
    geom geometry(MultiPolygon, 4326) NOT NULL,
    geom_simplified geometry(MultiPolygon, 4326),
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_territorio_jurisdicciones_codigo UNIQUE (codigo_jurisdiccion),
    CONSTRAINT uq_territorio_jurisdicciones_objectid UNIQUE (source_objectid),
    CONSTRAINT fk_territorio_jurisdicciones_region
        FOREIGN KEY (id_region)
        REFERENCES territorio_regiones (id_region),
    CONSTRAINT fk_territorio_jurisdicciones_division
        FOREIGN KEY (id_division)
        REFERENCES territorio_divisiones (id_division),
    CONSTRAINT fk_territorio_jurisdicciones_comisaria
        FOREIGN KEY (id_territorio_comisaria)
        REFERENCES territorio_comisarias (id_territorio_comisaria)
);

CREATE INDEX IF NOT EXISTS idx_territorio_jurisdicciones_region
    ON territorio_jurisdicciones (id_region);

CREATE INDEX IF NOT EXISTS idx_territorio_jurisdicciones_division
    ON territorio_jurisdicciones (id_division);

CREATE INDEX IF NOT EXISTS idx_territorio_jurisdicciones_comisaria
    ON territorio_jurisdicciones (id_territorio_comisaria);

CREATE INDEX IF NOT EXISTS idx_territorio_jurisdicciones_nombre
    ON territorio_jurisdicciones (nombre_normalizado);

CREATE INDEX IF NOT EXISTS idx_territorio_jurisdicciones_activo
    ON territorio_jurisdicciones (activo);

CREATE INDEX IF NOT EXISTS idx_territorio_jurisdicciones_geom_gist
    ON territorio_jurisdicciones
    USING GIST (geom);

CREATE INDEX IF NOT EXISTS idx_territorio_jurisdicciones_geom_simplified_gist
    ON territorio_jurisdicciones
    USING GIST (geom_simplified);


CREATE TABLE IF NOT EXISTS territorio_sectores (
    id_sector BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_region BIGINT NOT NULL,
    id_division BIGINT NOT NULL,
    id_territorio_comisaria BIGINT NOT NULL,
    source_objectid BIGINT,
    codigo_sector VARCHAR(40) NOT NULL,
    sector_codigo VARCHAR(20),
    label_sector VARCHAR(150) NOT NULL,
    label_normalizado VARCHAR(150) NOT NULL,
    clase_sector VARCHAR(50),
    codigo_unidad VARCHAR(20),
    codigo_inei VARCHAR(20),
    area_km2 NUMERIC(16,6),
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    source_properties JSONB NOT NULL DEFAULT '{}'::JSONB,
    geom geometry(MultiPolygon, 4326) NOT NULL,
    geom_simplified geometry(MultiPolygon, 4326),
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_territorio_sectores_codigo UNIQUE (codigo_sector),
    CONSTRAINT uq_territorio_sectores_objectid UNIQUE (source_objectid),
    CONSTRAINT fk_territorio_sectores_region
        FOREIGN KEY (id_region)
        REFERENCES territorio_regiones (id_region),
    CONSTRAINT fk_territorio_sectores_division
        FOREIGN KEY (id_division)
        REFERENCES territorio_divisiones (id_division),
    CONSTRAINT fk_territorio_sectores_comisaria
        FOREIGN KEY (id_territorio_comisaria)
        REFERENCES territorio_comisarias (id_territorio_comisaria)
);

CREATE INDEX IF NOT EXISTS idx_territorio_sectores_region
    ON territorio_sectores (id_region);

CREATE INDEX IF NOT EXISTS idx_territorio_sectores_division
    ON territorio_sectores (id_division);

CREATE INDEX IF NOT EXISTS idx_territorio_sectores_comisaria
    ON territorio_sectores (id_territorio_comisaria);

CREATE INDEX IF NOT EXISTS idx_territorio_sectores_label
    ON territorio_sectores (label_normalizado);

CREATE INDEX IF NOT EXISTS idx_territorio_sectores_activo
    ON territorio_sectores (activo);

CREATE INDEX IF NOT EXISTS idx_territorio_sectores_geom_gist
    ON territorio_sectores
    USING GIST (geom);

CREATE INDEX IF NOT EXISTS idx_territorio_sectores_geom_simplified_gist
    ON territorio_sectores
    USING GIST (geom_simplified);
